[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
    "python-dotenv",
    "requests>=2.34.2",
]

[tool.uv.sources]
python-dotenv = { git = "https://github.com/Okaz02/python-dotenv" }
