[project]
name = "camera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.104",
    "fastapi>=0.141.1",
    "python-dotenv-fixed",
]

[tool.uv.sources]
python-dotenv-fixed = { git = "https://github.com/Okaz02/python-dotenv" }
