services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: classee
      POSTGRES_USER: classee
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: